name: roboshop
services:
  mongodb:
    build : ./mongodb
    image: sadhanala529/mongodb:v1 # docker build -t sadhanala529/mongodb:v1
    container_name: mongodb #docker run -d --network roboshop sadhanala529/mongodb:v1
  catalogue:
    build: ./catalogue
    image: sadhanala529/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: ./user
    image: sadhanala529/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    build: ./cart
    image: sadhanala529/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
  shipping:
    build: ./shipping
    image: sadhanala529/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
  mysql:
    build: ./mysql
    image: sadhanala529/mysql
    container_name: mysql
    command: --mysql-native-password=ON --innodb-lock_wait_timeout=120
    environment:
      MYSQL_ROOT_PASSWORD: "RoboShop@1"
  redis:
    build: ./redis
    image: redis
    container_name: redis

  frontend:
    build: ./frontend
    image: sadhanala529/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
networks:
    default : #this means all the services in this file use thid network
      name: roboshop
      driver: bridge
      external: false # if true it should created manually , if false docker creates this network

