name: roboshop
services:
  mongodb:
    build : ./mongodb
    image: sadhanala529/mongodb:v1 # docker build -t sadhanala529/mongodb:v1
    container_name: mongodb #docker run -d --network roboshop sadhanala529/mongodb:v1
  catalogue:
    build: ./catalogue
    image: sadhanala529/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: ./user
    image: sadhanala529/user:v1
    Container_name: user
    depends_on:
      - redis
      - mongodb
  frontend:
    build: ./frontend
    image: sadhanala529/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
networks:
    default : #this means all the services in this file use thid network
      name: roboshop
      driver: bridge
      external: false # if true it should created manually , if false docker creates this network

